# Generated by Django 3.0.3 on 2020-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapy_manage',
            fields=[
                ('task_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('scrapy_id', models.CharField(blank=True, max_length=500, null=True)),
                ('scope', models.CharField(blank=True, max_length=2, null=True)),
                ('xsort', models.CharField(blank=True, max_length=2, null=True)),
                ('category', models.CharField(blank=True, max_length=2, null=True)),
                ('vip', models.CharField(blank=True, max_length=2, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('date_time_begin', models.CharField(blank=True, max_length=500, null=True)),
                ('date_time_end', models.CharField(blank=True, max_length=500, null=True)),
                ('real_time_task', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'scrapy_manage',
            },
        ),
        migrations.CreateModel(
            name='weibo_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('fans_num', models.IntegerField(blank=True, null=True)),
                ('authentication', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'weibo_user',
            },
        ),
        migrations.CreateModel(
            name='weibo_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('post_id', models.CharField(max_length=100)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('forward_num', models.IntegerField(blank=True, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('repost_id', models.CharField(blank=True, max_length=20, null=True)),
                ('task_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'weibo_post',
                'unique_together': {('post_id', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='noise_judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('noise', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'noise_judge',
                'unique_together': {('post_id', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('cluster', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'event',
                'unique_together': {('post_id', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'category',
                'unique_together': {('post_id', 'task_id')},
            },
        ),
    ]
